version : "3"
services :
  nginx:
    image: docker.io/nginx:latest
    container_name: nginx_container
    volumes:
      - ./nginx:/etc/nginx:z
      - ./conf:/etc/nginx/conf:z
      - ./certs:/certs:z
    ports:
      - 80:80
      - 443:443

