version: '3'
services:
    db:
        image: postgres:13
        volumes:
            - ./db:/var/lib/postgresql/data:z
        ports:
            - "5432:5432"
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_DB=${DB_NAME}
    app:
        image: joplin/server:latest
        depends_on:
            - db
        ports:
            - "22300:22300"
            - 41184:41184
        restart: unless-stopped
        environment:
            - APP_PORT=22300
            - APP_BASE_URL=https://therhys.co.uk/notes
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_DATABASE=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=db
