version: '3.2'
services:
  jellyfin:
    image: docker.io/jellyfin/jellyfin
    container_name: jellyfin
    user: 0:0
    ports:
      - 8096:8096
    volumes:
      - ./config:/config:z
      - ./cache:/cache:z
      - /mnt/share/TV:/TV:z
      - /mnt/share/Movies:/Movies:z
      - /mnt/share/Music:/Music:z
    restart: 'unless-stopped'
#    Optional - alternative address used for autodiscovery
#    environment:
#      - JELLYFIN_PublishedServerUrl=http://example.com
