version: '3.2'

services:
  rhysa:
    image: cloudflare/cloudflared
    user: 0:0
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./rhysa:/etc/cloudflared:z
    command: tunnel run
  therhys:
    image: cloudflare/cloudflared
    user: 0:0
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./therhys:/etc/cloudflared:z
    command: tunnel run
