version: "3.7"
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:nightly
    ports:
        - "9925:9000"
    depends_on:
      - postgres
    volumes:
      - ./data:/app/data/:z
    environment:
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Londom
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://therhys.co.uk/mealie

      - DB_ENGINE=postgres
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mealie
    restart: always
  postgres:
    container_name: postgres
    image: postgres:15
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data:z
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
