version: '2'

services:
  db:
    image: docker.io/mariadb:10.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./db:/var/lib/mysql:z
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PW}
      - MYSQL_PASSWORD=${DB_PW}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}

  app:
    image: docker.io/nextcloud:latest
    restart: always
    ports:
      - 8000:80
    links:
      - db
    volumes:
      - ./cloud:/var/www/html:z
    environment:
      - MYSQL_PASSWORD=${DB_ROOT_PW}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_HOST=db
      - OVERWRITEWEBROOT=/cloud
      - OVERWRITEHOST=therhys.co.uk
      - OVERWRITEPROTOCOL=https
